import {
  UserAccount,
  Department,
  Employee,
  Lead,
  FollowUp,
  Customer,
  ServiceCatalogItem,
  Quotation,
  Project,
  Milestone,
  Task,
  Timesheet,
  Invoice,
  Payment,
  Expense,
  Transaction,
  SalesTarget,
  InventoryProduct,
  StockMovement,
  Vendor,
  PurchaseOrder,
  SupportTicket,
  ErpDocument,
  NotificationItem,
  AuditLog,
  CommunicationEvent,
} from '../types/erp';

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'USR-1',
    name: 'Mr. Dhanunjay',
    email: 'dhanu@ddsexpo.com',
    avatar: '/assets/img/team/team-1.png',
    role: 'Super Admin',
    departmentId: 'DEP-MGMT',
    employeeId: 'EMP-01',
  },
  {
    id: 'USR-2',
    name: 'Mr. Srikanth',
    email: 'srikanth@ddsexpo.com',
    avatar: '/assets/img/team/team-3.png',
    role: 'Manager',
    departmentId: 'DEP-DEV',
    employeeId: 'EMP-03',
  },
  {
    id: 'USR-3',
    name: 'Mr. Sanjay Kumar',
    email: 'sanjay@ddsexpo.com',
    avatar: '/assets/img/team/team-4.png',
    role: 'Sales',
    departmentId: 'DEP-SALES',
    employeeId: 'EMP-04',
  },
  {
    id: 'USR-4',
    name: 'Mrs. Rama Devi',
    email: 'ramadevi@ddsexpo.com',
    avatar: '/assets/img/team/team-2.png',
    role: 'HR',
    departmentId: 'DEP-HR',
    employeeId: 'EMP-02',
  },
  {
    id: 'USR-5',
    name: 'Alex Rivera',
    email: 'alex.dev@ddsexpo.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'Developer',
    departmentId: 'DEP-DEV',
    employeeId: 'EMP-05',
  },
  {
    id: 'USR-6',
    name: 'Priya Sharma',
    email: 'priya.accounts@ddsexpo.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'Accounts',
    departmentId: 'DEP-FIN',
    employeeId: 'EMP-06',
  },
  {
    id: 'USR-7',
    name: 'Kiran Varma',
    email: 'kiran.support@ddsexpo.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'Support',
    departmentId: 'DEP-SUPP',
    employeeId: 'EMP-07',
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  { id: 'DEP-MGMT', name: 'Management', headName: 'Mr. Dhanunjay', employeeCount: 3 },
  { id: 'DEP-SALES', name: 'Sales & Business', headName: 'Mr. Sanjay', employeeCount: 5 },
  { id: 'DEP-DEV', name: 'Development & Tech', headName: 'Mr. Srikanth', employeeCount: 6 },
  { id: 'DEP-AI', name: 'AI & Automation Labs', headName: 'Mr. Dhanunjay', employeeCount: 4 },
  { id: 'DEP-MKTG', name: 'Digital Marketing', headName: 'Sneha Patel', employeeCount: 4 },
  { id: 'DEP-FIN', name: 'Finance & Accounts', headName: 'Priya Sharma', employeeCount: 2 },
  { id: 'DEP-HR', name: 'Human Resources', headName: 'Mrs. Rama Devi', employeeCount: 2 },
  { id: 'DEP-SUPP', name: 'Customer Support', headName: 'Kiran Varma', employeeCount: 3 },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'EMP-01',
    name: 'Mr. Dhanunjay',
    email: 'dhanu@ddsexpo.com',
    phone: '+91 9966994679',
    department: 'Management',
    designation: 'Founder & CEO',
    joiningDate: '2023-01-10',
    role: 'Super Admin',
    status: 'Active',
    monthlySalary: 150000,
    avatar: '/assets/img/team/team-1.png',
  },
  {
    id: 'EMP-02',
    name: 'Mrs. Rama Devi',
    email: 'ramadevi@ddsexpo.com',
    phone: '+91 9618231993',
    department: 'Human Resources',
    designation: 'Director & HR Head',
    joiningDate: '2023-01-15',
    role: 'HR',
    status: 'Active',
    monthlySalary: 110000,
    avatar: '/assets/img/team/team-2.png',
  },
  {
    id: 'EMP-03',
    name: 'Mr. Srikanth',
    email: 'srikanth@ddsexpo.com',
    phone: '+91 9848022331',
    department: 'Development & Tech',
    designation: 'Chief Technology Advisor & PM',
    joiningDate: '2023-03-01',
    role: 'Manager',
    status: 'Active',
    monthlySalary: 125000,
    avatar: '/assets/img/team/team-3.png',
  },
  {
    id: 'EMP-04',
    name: 'Mr. Sanjay Kumar',
    email: 'sanjay@ddsexpo.com',
    phone: '+91 9123456780',
    department: 'Sales & Business',
    designation: 'Lead Business Executive',
    joiningDate: '2023-05-12',
    role: 'Sales',
    status: 'Active',
    monthlySalary: 75000,
    avatar: '/assets/img/team/team-4.png',
  },
  {
    id: 'EMP-05',
    name: 'Alex Rivera',
    email: 'alex.dev@ddsexpo.com',
    phone: '+91 9700112233',
    department: 'Development & Tech',
    designation: 'Senior Full Stack & AI Engineer',
    joiningDate: '2023-08-01',
    role: 'Developer',
    status: 'Active',
    monthlySalary: 85000,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'EMP-06',
    name: 'Priya Sharma',
    email: 'priya.accounts@ddsexpo.com',
    phone: '+91 9811223344',
    department: 'Finance & Accounts',
    designation: 'Senior Accounts Officer',
    joiningDate: '2023-09-15',
    role: 'Accounts',
    status: 'Active',
    monthlySalary: 65000,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'EMP-07',
    name: 'Kiran Varma',
    email: 'kiran.support@ddsexpo.com',
    phone: '+91 9900334455',
    department: 'Customer Support',
    designation: 'Client Success & Support Lead',
    joiningDate: '2024-01-10',
    role: 'Support',
    status: 'Active',
    monthlySalary: 50000,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_SERVICES: ServiceCatalogItem[] = [
  {
    id: 'SRV-01',
    name: 'AI-Powered Digital Marketing Funnels',
    description: 'Multi-channel algorithmic Meta & Google Ad funnels with continuous A/B testing.',
    category: 'Digital Marketing',
    basePrice: 45000,
    pricingType: 'Monthly Retainer',
    taxPercent: 18,
    discountPercent: 5,
    deliveryTimeline: '15 Days Setup',
    status: 'Active',
  },
  {
    id: 'SRV-02',
    name: 'Custom E-Commerce & Web Portal',
    description: 'High-converting Next.js / React full-stack portal with payment gateway & inventory sync.',
    category: 'Web & Tech',
    basePrice: 120000,
    pricingType: 'Fixed',
    taxPercent: 18,
    discountPercent: 10,
    deliveryTimeline: '30 Working Days',
    status: 'Active',
  },
  {
    id: 'SRV-03',
    name: 'AI Agent & Workflow Automation Suite',
    description: 'Custom autonomous LLM agents for customer support, automated CRM data routing & WhatsApp bots.',
    category: 'AI Solutions',
    basePrice: 85000,
    pricingType: 'Fixed',
    taxPercent: 18,
    discountPercent: 0,
    deliveryTimeline: '20 Days',
    status: 'Active',
  },
  {
    id: 'SRV-04',
    name: 'AI Creatives, Reels & Video Production',
    description: 'Monthly production of 30 AI reels, short-form viral videos, and hyper-targeted ad banners.',
    category: 'Design & Creative',
    basePrice: 35000,
    pricingType: 'Monthly Retainer',
    taxPercent: 18,
    discountPercent: 5,
    deliveryTimeline: 'Monthly continuous',
    status: 'Active',
  },
  {
    id: 'SRV-05',
    name: 'Cloud Infrastructure & 24/7 Server SLA',
    description: 'Managed Kubernetes / Cloud Run deployment, zero-downtime backups, and WAF security.',
    category: 'Cloud & Maintenance',
    basePrice: 25000,
    pricingType: 'Monthly Retainer',
    taxPercent: 18,
    discountPercent: 0,
    deliveryTimeline: 'Immediate',
    status: 'Active',
  },
  {
    id: 'SRV-06',
    name: 'Complete Brand Identity & UI/UX Design',
    description: 'Comprehensive brand bible, logo vectors, Figma design systems, and marketing collateral.',
    category: 'Design & Creative',
    basePrice: 50000,
    pricingType: 'Fixed',
    taxPercent: 18,
    discountPercent: 10,
    deliveryTimeline: '14 Days',
    status: 'Active',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'CUST-501',
    name: 'Mr. Arjun Sharma',
    company: 'Vizag Port Logistics Ltd',
    phone: '+91 9848011223',
    email: 'arjun@vizaglogistics.in',
    address: 'D.No 48-12-5, Siripuram, Visakhapatnam, AP 530003',
    gstNumber: '37AAAAA0000A1Z5',
    createdAt: '2026-06-10',
    servicesPurchased: ['Custom E-Commerce & Web Portal', 'AI-Powered Digital Marketing Funnels'],
    totalBusinessValue: 165000,
    status: 'VIP',
  },
  {
    id: 'CUST-502',
    name: 'Ritika Rao',
    company: 'Aura Organic Health',
    phone: '+91 9988776655',
    email: 'ritika@aurawellness.com',
    address: 'Plot 14, Hitech City Phase 2, Hyderabad, TS 500081',
    gstNumber: '36BBBBB1111B1Z2',
    createdAt: '2026-07-04',
    servicesPurchased: ['AI Creatives, Reels & Video Production', 'Digital Marketing'],
    totalBusinessValue: 70000,
    status: 'Active',
  },
  {
    id: 'CUST-503',
    name: 'Vikram Sethi',
    company: 'Sethi Retail Network',
    phone: '+91 9810234567',
    email: 'vikram@sethiretail.com',
    address: 'Connaught Place Block B, New Delhi 110001',
    gstNumber: '07CCCCC2222C1Z8',
    createdAt: '2026-07-22',
    servicesPurchased: ['AI Agent & Workflow Automation Suite'],
    totalBusinessValue: 85000,
    status: 'Active',
  },
  {
    id: 'CUST-504',
    name: 'Dr. Rahul Mehra',
    company: 'Mehra Specialty Clinics',
    phone: '+91 9723456789',
    email: 'rahul@mehraclinics.org',
    address: 'FC Road, Shivaji Nagar, Pune, MH 411005',
    gstNumber: '27DDDDD3333D1Z1',
    createdAt: '2026-08-01',
    servicesPurchased: ['AI-Powered Digital Marketing Funnels'],
    totalBusinessValue: 45000,
    status: 'Active',
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'LEAD-101',
    name: 'Kavita Reddy',
    company: 'Reddy Grand Jewels',
    phone: '+91 9849112244',
    email: 'kavita@reddyjewels.com',
    location: 'Visakhapatnam',
    source: 'Website',
    interestedService: 'AI Creatives, Reels & Video Production',
    leadValue: 60000,
    assignedEmployeeId: 'EMP-04',
    assignedEmployeeName: 'Mr. Sanjay Kumar',
    priority: 'High',
    status: 'Negotiation',
    createdDate: '2026-09-10',
    lastContact: '2026-09-17',
    nextFollowUp: '2026-09-19',
    notes: 'Requested custom monthly reel generation for festival campaign. Pricing discussed.',
  },
  {
    id: 'LEAD-102',
    name: 'Manish Verma',
    company: 'Apex Cloud Solutions',
    phone: '+91 9822334455',
    email: 'manish@apexcloud.co',
    location: 'Bengaluru',
    source: 'Google',
    interestedService: 'AI Agent & Workflow Automation Suite',
    leadValue: 95000,
    assignedEmployeeId: 'EMP-04',
    assignedEmployeeName: 'Mr. Sanjay Kumar',
    priority: 'Urgent',
    status: 'Proposal Sent',
    createdDate: '2026-09-12',
    lastContact: '2026-09-16',
    nextFollowUp: '2026-09-18',
    notes: 'Looking to automate tier-1 customer inquiries on their SaaS tool. Proposal QT-2026-004 sent.',
  },
  {
    id: 'LEAD-103',
    name: 'Sneha Chawla',
    company: 'Zenith Fashion House',
    phone: '+91 9711223344',
    email: 'sneha@zenithstyles.in',
    location: 'Mumbai',
    source: 'Instagram',
    interestedService: 'Custom E-Commerce & Web Portal',
    leadValue: 140000,
    assignedEmployeeId: 'EMP-04',
    assignedEmployeeName: 'Mr. Sanjay Kumar',
    priority: 'Medium',
    status: 'Interested',
    createdDate: '2026-09-14',
    lastContact: '2026-09-15',
    nextFollowUp: '2026-09-20',
    notes: 'Wants Shopify migration to headless Next.js web application with 3D product previews.',
  },
  {
    id: 'LEAD-104',
    name: 'Sunil Jagtap',
    company: 'Jagtap Agro Impex',
    phone: '+91 9655443322',
    email: 'sunil@jagtapimpex.com',
    location: 'Pune',
    source: 'Referral',
    interestedService: 'AI-Powered Digital Marketing Funnels',
    leadValue: 45000,
    assignedEmployeeId: 'EMP-04',
    assignedEmployeeName: 'Mr. Sanjay Kumar',
    priority: 'Low',
    status: 'Contacted',
    createdDate: '2026-09-15',
    lastContact: '2026-09-16',
    nextFollowUp: '2026-09-21',
    notes: 'Referred by Rahul Mehra. Exploring export buyer generation through LinkedIn and Meta ads.',
  },
  {
    id: 'LEAD-105',
    name: 'Deepak Vats',
    company: 'CyberShield Security',
    phone: '+91 9911002233',
    email: 'deepak@cybershield.in',
    location: 'Hyderabad',
    source: 'WhatsApp',
    interestedService: 'Complete Brand Identity & UI/UX Design',
    leadValue: 50000,
    assignedEmployeeId: 'EMP-04',
    assignedEmployeeName: 'Mr. Sanjay Kumar',
    priority: 'Medium',
    status: 'New',
    createdDate: '2026-09-18',
    lastContact: '2026-09-18',
    nextFollowUp: '2026-09-18',
    notes: 'Inquired via WhatsApp for corporate identity redesign before upcoming angel funding.',
  },
];

export const INITIAL_FOLLOWUPS: FollowUp[] = [
  {
    id: 'FLP-201',
    leadId: 'LEAD-102',
    leadName: 'Manish Verma (Apex Cloud)',
    date: '2026-09-18',
    time: '11:30',
    employeeId: 'EMP-04',
    employeeName: 'Mr. Sanjay Kumar',
    type: 'Video Call',
    notes: 'Review AI workflow automation scope and finalize contract terms.',
    status: 'Pending',
  },
  {
    id: 'FLP-202',
    leadId: 'LEAD-105',
    leadName: 'Deepak Vats (CyberShield)',
    date: '2026-09-18',
    time: '15:00',
    employeeId: 'EMP-04',
    employeeName: 'Mr. Sanjay Kumar',
    type: 'Phone Call',
    notes: 'Initial discovery call regarding brand identity overhaul & deliverables schedule.',
    status: 'Pending',
  },
  {
    id: 'FLP-203',
    leadId: 'LEAD-101',
    leadName: 'Kavita Reddy (Reddy Jewels)',
    date: '2026-09-19',
    time: '14:00',
    employeeId: 'EMP-04',
    employeeName: 'Mr. Sanjay Kumar',
    type: 'Meeting',
    notes: 'Meet at Visakhapatnam showroom to demonstrate AI reels sample preview.',
    status: 'Pending',
  },
  {
    id: 'FLP-204',
    leadId: 'LEAD-104',
    leadName: 'Sunil Jagtap',
    date: '2026-09-16',
    time: '10:00',
    employeeId: 'EMP-04',
    employeeName: 'Mr. Sanjay Kumar',
    type: 'Phone Call',
    notes: 'Followed up on lead generation audit report. Client requested time until Monday.',
    outcome: 'Sent budget breakdown sheet.',
    status: 'Completed',
  },
];

export const INITIAL_QUOTATIONS: Quotation[] = [
  {
    id: 'QT-2026-001',
    customerId: 'CUST-501',
    customerName: 'Mr. Arjun Sharma',
    customerCompany: 'Vizag Port Logistics Ltd',
    customerEmail: 'arjun@vizaglogistics.in',
    customerPhone: '+91 9848011223',
    customerAddress: 'D.No 48-12-5, Siripuram, Visakhapatnam, AP',
    date: '2026-06-15',
    validUntil: '2026-07-15',
    items: [
      {
        id: 'QI-1',
        serviceName: 'Custom E-Commerce & Web Portal',
        description: 'B2B Cargo booking portal with real-time vessel tracking and GST invoice auto-generation.',
        quantity: 1,
        unitPrice: 120000,
        discountPercent: 10,
        taxPercent: 18,
        total: 127440,
      },
      {
        id: 'QI-2',
        serviceName: 'AI-Powered Digital Marketing Funnels',
        description: 'First month onboarding & Google Search campaigns setup.',
        quantity: 1,
        unitPrice: 45000,
        discountPercent: 5,
        taxPercent: 18,
        total: 50445,
      },
    ],
    subtotal: 150750,
    taxAmount: 27135,
    discountAmount: 14250,
    grandTotal: 177885,
    terms: '50% advance on project kickoff, 30% on staging delivery, 20% on live launch.',
    notes: 'Approved with priority support SLA.',
    status: 'Accepted',
    associatedProjectId: 'PRJ-401',
  },
  {
    id: 'QT-2026-002',
    customerId: 'CUST-502',
    customerName: 'Ritika Rao',
    customerCompany: 'Aura Organic Health',
    customerEmail: 'ritika@aurawellness.com',
    customerPhone: '+91 9988776655',
    customerAddress: 'Plot 14, Hitech City, Hyderabad, TS',
    date: '2026-07-06',
    validUntil: '2026-08-06',
    items: [
      {
        id: 'QI-3',
        serviceName: 'AI Creatives, Reels & Video Production',
        description: 'Quarterly social media AI video and graphics package (90 assets total).',
        quantity: 3,
        unitPrice: 35000,
        discountPercent: 10,
        taxPercent: 18,
        total: 111510,
      },
    ],
    subtotal: 94500,
    taxAmount: 17010,
    discountAmount: 10500,
    grandTotal: 111510,
    terms: 'Monthly payment on 1st of every month.',
    notes: 'Includes dedicated account manager.',
    status: 'Accepted',
    associatedProjectId: 'PRJ-402',
  },
  {
    id: 'QT-2026-003',
    customerId: 'CUST-503',
    customerName: 'Vikram Sethi',
    customerCompany: 'Sethi Retail Network',
    customerEmail: 'vikram@sethiretail.com',
    customerPhone: '+91 9810234567',
    customerAddress: 'Connaught Place, New Delhi',
    date: '2026-07-25',
    validUntil: '2026-08-25',
    items: [
      {
        id: 'QI-4',
        serviceName: 'AI Agent & Workflow Automation Suite',
        description: 'Omnichannel WhatsApp AI bot integrated with inventory POS and order status lookup.',
        quantity: 1,
        unitPrice: 85000,
        discountPercent: 0,
        taxPercent: 18,
        total: 100300,
      },
    ],
    subtotal: 85000,
    taxAmount: 15300,
    discountAmount: 0,
    grandTotal: 100300,
    terms: 'Advance 50%, remaining on completion.',
    notes: 'Integration with existing Tally POS system.',
    status: 'Accepted',
    associatedProjectId: 'PRJ-403',
  },
  {
    id: 'QT-2026-004',
    customerId: 'CUST-504',
    customerName: 'Manish Verma',
    customerCompany: 'Apex Cloud Solutions',
    customerEmail: 'manish@apexcloud.co',
    customerPhone: '+91 9822334455',
    customerAddress: 'Indiranagar, Bengaluru, KA',
    date: '2026-09-14',
    validUntil: '2026-10-14',
    items: [
      {
        id: 'QI-5',
        serviceName: 'AI Agent & Workflow Automation Suite',
        description: 'Customer Support Autonomous Agent with Slack & Zendesk sync.',
        quantity: 1,
        unitPrice: 85000,
        discountPercent: 5,
        taxPercent: 18,
        total: 95285,
      },
    ],
    subtotal: 80750,
    taxAmount: 14535,
    discountAmount: 4250,
    grandTotal: 95285,
    terms: 'Net 15 days from acceptance.',
    notes: 'Special early adopter discount applied.',
    status: 'Sent',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'PRJ-401',
    name: 'Vizag Port Logistics Web Portal & Booking App',
    customerId: 'CUST-501',
    customerName: 'Mr. Arjun Sharma (Vizag Port Logistics Ltd)',
    service: 'Custom E-Commerce & Web Portal',
    projectManagerId: 'EMP-03',
    projectManagerName: 'Mr. Srikanth',
    teamMemberIds: ['EMP-03', 'EMP-05'],
    startDate: '2026-06-20',
    deadline: '2026-09-30',
    budget: 165000,
    status: 'Testing',
    progress: 85,
    description: 'B2B portal allowing maritime clients to book container clearances, track berth availability, and pay port dues.',
    quotationId: 'QT-2026-001',
  },
  {
    id: 'PRJ-402',
    name: 'Aura Organic Viral Reels & Growth Campaign',
    customerId: 'CUST-502',
    customerName: 'Ritika Rao (Aura Organic Health)',
    service: 'AI Creatives, Reels & Video Production',
    projectManagerId: 'EMP-04',
    projectManagerName: 'Mr. Sanjay Kumar',
    teamMemberIds: ['EMP-04', 'EMP-05'],
    startDate: '2026-07-10',
    deadline: '2026-10-10',
    budget: 105000,
    status: 'Active',
    progress: 65,
    description: 'Production of 90 high-retention AI videos, voiceovers in Hindi & English, promoting organic superfoods.',
    quotationId: 'QT-2026-002',
  },
  {
    id: 'PRJ-403',
    name: 'Sethi Retail WhatsApp AI Bot Engine',
    customerId: 'CUST-503',
    customerName: 'Vikram Sethi (Sethi Retail Network)',
    service: 'AI Agent & Workflow Automation Suite',
    projectManagerId: 'EMP-03',
    projectManagerName: 'Mr. Srikanth',
    teamMemberIds: ['EMP-03', 'EMP-05'],
    startDate: '2026-08-01',
    deadline: '2026-09-25',
    budget: 85000,
    status: 'Client Review',
    progress: 90,
    description: 'AI conversational agent connected with WhatsApp Business API allowing automated product catalog browsing.',
    quotationId: 'QT-2026-003',
  },
];

export const INITIAL_MILESTONES: Milestone[] = [
  {
    id: 'MLS-1',
    projectId: 'PRJ-401',
    title: 'UI/UX Prototypes & Architecture Blueprint',
    dueDate: '2026-07-15',
    completed: true,
  },
  {
    id: 'MLS-2',
    projectId: 'PRJ-401',
    title: 'Vessel Tracking API & Core Database Schema',
    dueDate: '2026-08-15',
    completed: true,
  },
  {
    id: 'MLS-3',
    projectId: 'PRJ-401',
    title: 'Payment Gateway Integration & QA Penetration Testing',
    dueDate: '2026-09-20',
    completed: false,
  },
  {
    id: 'MLS-4',
    projectId: 'PRJ-403',
    title: 'WhatsApp Cloud API Webhook Integration',
    dueDate: '2026-08-20',
    completed: true,
  },
  {
    id: 'MLS-5',
    projectId: 'PRJ-403',
    title: 'Catalog Search & Natural Language Query Grounding',
    dueDate: '2026-09-10',
    completed: true,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'TSK-1001',
    title: 'Implement Razorpay & ICICI Direct Gateway Webhooks',
    description: 'Secure payment verification endpoint with signature verification for PRJ-401.',
    projectId: 'PRJ-401',
    projectName: 'Vizag Port Logistics Web Portal',
    assignedEmployeeId: 'EMP-05',
    assignedEmployeeName: 'Alex Rivera',
    priority: 'Urgent',
    startDate: '2026-09-15',
    deadline: '2026-09-20',
    status: 'In Progress',
    progress: 75,
    comments: [
      {
        id: 'C-1',
        authorName: 'Mr. Srikanth',
        date: '2026-09-16 14:20',
        content: 'Ensure all sandbox test webhooks return idempotent 200 OK responses.',
      },
    ],
  },
  {
    id: 'TSK-1002',
    title: 'Dockerize Production Container for Cloud Run Deploy',
    description: 'Set up multi-stage node container with slim footprint and health check probes.',
    projectId: 'PRJ-401',
    projectName: 'Vizag Port Logistics Web Portal',
    assignedEmployeeId: 'EMP-05',
    assignedEmployeeName: 'Alex Rivera',
    priority: 'High',
    startDate: '2026-09-16',
    deadline: '2026-09-22',
    status: 'To Do',
    progress: 0,
    comments: [],
  },
  {
    id: 'TSK-1003',
    title: 'Batch Render 30 AI Voiceover Health Clips',
    description: 'Generate high-definition vertical 9:16 videos with auto-subtitles for Aura Organic.',
    projectId: 'PRJ-402',
    projectName: 'Aura Organic Viral Reels',
    assignedEmployeeId: 'EMP-04',
    assignedEmployeeName: 'Mr. Sanjay Kumar',
    priority: 'Medium',
    startDate: '2026-09-10',
    deadline: '2026-09-21',
    status: 'In Progress',
    progress: 60,
    comments: [],
  },
  {
    id: 'TSK-1004',
    title: 'Final Client Demo with Vikram Sethi',
    description: 'Conduct live WhatsApp ordering walkthrough with client management team.',
    projectId: 'PRJ-403',
    projectName: 'Sethi Retail WhatsApp AI Bot Engine',
    assignedEmployeeId: 'EMP-03',
    assignedEmployeeName: 'Mr. Srikanth',
    priority: 'High',
    startDate: '2026-09-17',
    deadline: '2026-09-19',
    status: 'Review',
    progress: 95,
    comments: [],
  },
  {
    id: 'TSK-1005',
    title: 'Build PostgreSQL Schema & Migrations',
    description: 'Initial table definitions for user session data and logistics tracking.',
    projectId: 'PRJ-401',
    projectName: 'Vizag Port Logistics Web Portal',
    assignedEmployeeId: 'EMP-05',
    assignedEmployeeName: 'Alex Rivera',
    priority: 'High',
    startDate: '2026-07-01',
    deadline: '2026-07-10',
    status: 'Completed',
    progress: 100,
    comments: [],
  },
];

export const INITIAL_TIMESHEETS: Timesheet[] = [
  {
    id: 'TS-01',
    employeeId: 'EMP-05',
    employeeName: 'Alex Rivera',
    projectId: 'PRJ-401',
    projectName: 'Vizag Port Logistics Web Portal',
    taskId: 'TSK-1001',
    date: '2026-09-17',
    hours: 6.5,
    description: 'Writing webhook validation and test suite for gateway',
    isBillable: true,
  },
  {
    id: 'TS-02',
    employeeId: 'EMP-03',
    employeeName: 'Mr. Srikanth',
    projectId: 'PRJ-403',
    projectName: 'Sethi Retail WhatsApp AI Bot Engine',
    taskId: 'TSK-1004',
    date: '2026-09-17',
    hours: 4.0,
    description: 'Staging environment dry run and load test',
    isBillable: true,
  },
  {
    id: 'TS-03',
    employeeId: 'EMP-04',
    employeeName: 'Mr. Sanjay Kumar',
    projectId: 'PRJ-402',
    projectName: 'Aura Organic Viral Reels',
    taskId: 'TSK-1003',
    date: '2026-09-16',
    hours: 5.5,
    description: 'Prompt engineering and image upscaling for video reels',
    isBillable: true,
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'INV-2026-101',
    quotationId: 'QT-2026-001',
    projectId: 'PRJ-401',
    projectName: 'Vizag Port Logistics Web Portal',
    customerId: 'CUST-501',
    customerName: 'Mr. Arjun Sharma',
    customerCompany: 'Vizag Port Logistics Ltd',
    customerEmail: 'arjun@vizaglogistics.in',
    customerAddress: 'Siripuram, Visakhapatnam, AP',
    issueDate: '2026-06-25',
    dueDate: '2026-07-10',
    items: [
      {
        id: 'II-1',
        description: 'Kickoff Advance (50%) - Web Portal & AI Marketing Funnel',
        quantity: 1,
        unitPrice: 88942.5,
        total: 88942.5,
      },
    ],
    subtotal: 88942.5,
    tax: 0,
    discount: 0,
    total: 88942.5,
    amountPaid: 88942.5,
    balanceDue: 0,
    status: 'Paid',
    paymentInstructions: 'Account Name: DDS Expo Technologies\nBank: HDFC Bank, Visakhapatnam\nIFSC: HDFC0001234\nA/C No: 50200088991122',
    terms: 'Payment due within 15 days of invoice date.',
  },
  {
    id: 'INV-2026-102',
    quotationId: 'QT-2026-001',
    projectId: 'PRJ-401',
    projectName: 'Vizag Port Logistics Web Portal',
    customerId: 'CUST-501',
    customerName: 'Mr. Arjun Sharma',
    customerCompany: 'Vizag Port Logistics Ltd',
    customerEmail: 'arjun@vizaglogistics.in',
    customerAddress: 'Siripuram, Visakhapatnam, AP',
    issueDate: '2026-09-01',
    dueDate: '2026-09-15',
    items: [
      {
        id: 'II-2',
        description: 'Milestone 2 Delivery (30%) - Staging Deployment & Gateway',
        quantity: 1,
        unitPrice: 53365.5,
        total: 53365.5,
      },
    ],
    subtotal: 53365.5,
    tax: 0,
    discount: 0,
    total: 53365.5,
    amountPaid: 0,
    balanceDue: 53365.5,
    status: 'Overdue',
    paymentInstructions: 'Account Name: DDS Expo Technologies\nBank: HDFC Bank, Visakhapatnam\nIFSC: HDFC0001234\nA/C No: 50200088991122',
    terms: 'Please settle overdue milestone to enable production DNS propagation.',
  },
  {
    id: 'INV-2026-103',
    quotationId: 'QT-2026-002',
    projectId: 'PRJ-402',
    projectName: 'Aura Organic Viral Reels',
    customerId: 'CUST-502',
    customerName: 'Ritika Rao',
    customerCompany: 'Aura Organic Health',
    customerEmail: 'ritika@aurawellness.com',
    customerAddress: 'Hitech City, Hyderabad, TS',
    issueDate: '2026-08-01',
    dueDate: '2026-08-15',
    items: [
      {
        id: 'II-3',
        description: 'Month 1 Retainer - 30 AI Video Reels & Meta Ads management',
        quantity: 1,
        unitPrice: 37170,
        total: 37170,
      },
    ],
    subtotal: 37170,
    tax: 0,
    discount: 0,
    total: 37170,
    amountPaid: 37170,
    balanceDue: 0,
    status: 'Paid',
    paymentInstructions: 'Account Name: DDS Expo Technologies\nBank: HDFC Bank, Visakhapatnam',
    terms: 'Monthly payment on 1st of month.',
  },
  {
    id: 'INV-2026-104',
    quotationId: 'QT-2026-003',
    projectId: 'PRJ-403',
    projectName: 'Sethi Retail WhatsApp AI Bot Engine',
    customerId: 'CUST-503',
    customerName: 'Vikram Sethi',
    customerCompany: 'Sethi Retail Network',
    customerEmail: 'vikram@sethiretail.com',
    customerAddress: 'Connaught Place, New Delhi',
    issueDate: '2026-08-10',
    dueDate: '2026-08-25',
    items: [
      {
        id: 'II-4',
        description: 'Initial Advance (50%) - AI Bot Architecture & POS Sync',
        quantity: 1,
        unitPrice: 50150,
        total: 50150,
      },
    ],
    subtotal: 50150,
    tax: 0,
    discount: 0,
    total: 50150,
    amountPaid: 50150,
    balanceDue: 0,
    status: 'Paid',
    paymentInstructions: 'Account Name: DDS Expo Technologies',
    terms: '50% advance received.',
  },
  {
    id: 'INV-2026-105',
    quotationId: 'QT-2026-003',
    projectId: 'PRJ-403',
    projectName: 'Sethi Retail WhatsApp AI Bot Engine',
    customerId: 'CUST-503',
    customerName: 'Vikram Sethi',
    customerCompany: 'Sethi Retail Network',
    customerEmail: 'vikram@sethiretail.com',
    customerAddress: 'Connaught Place, New Delhi',
    issueDate: '2026-09-16',
    dueDate: '2026-09-30',
    items: [
      {
        id: 'II-5',
        description: 'Final Milestone (50%) - Launch & Staff Handover',
        quantity: 1,
        unitPrice: 50150,
        total: 50150,
      },
    ],
    subtotal: 50150,
    tax: 0,
    discount: 0,
    total: 50150,
    amountPaid: 0,
    balanceDue: 50150,
    status: 'Sent',
    paymentInstructions: 'Account Name: DDS Expo Technologies',
    terms: 'Due on production signoff.',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'PAY-901',
    invoiceId: 'INV-2026-101',
    customerId: 'CUST-501',
    customerName: 'Mr. Arjun Sharma (Vizag Port Logistics)',
    amount: 88942.5,
    paymentDate: '2026-06-28',
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'NEFT-HDFC-99881122',
    notes: 'Advance clearance payment received.',
  },
  {
    id: 'PAY-902',
    invoiceId: 'INV-2026-103',
    customerId: 'CUST-502',
    customerName: 'Ritika Rao (Aura Organic)',
    amount: 37170,
    paymentDate: '2026-08-04',
    paymentMethod: 'UPI / GPay',
    referenceNumber: 'UPI-RAZOR-445566',
    notes: 'Month 1 retainer settled via UPI.',
  },
  {
    id: 'PAY-903',
    invoiceId: 'INV-2026-104',
    customerId: 'CUST-503',
    customerName: 'Vikram Sethi (Sethi Retail)',
    amount: 50150,
    paymentDate: '2026-08-12',
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'RTGS-ICICI-009988',
    notes: '50% project deposit received.',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'EXP-701',
    category: 'Cloud & Servers',
    amount: 14200,
    date: '2026-09-02',
    vendorName: 'Google Cloud & AWS India',
    description: 'Server instances, GPU compute for model inferences, and Cloud SQL backup storage.',
  },
  {
    id: 'EXP-702',
    category: 'Software Licenses',
    amount: 18500,
    date: '2026-09-05',
    vendorName: 'OpenAI, Midjourney & Figma',
    description: 'Enterprise API credits, image synthesis rendering licenses, and UI design seats.',
  },
  {
    id: 'EXP-703',
    category: 'Office & Utilities',
    amount: 22000,
    date: '2026-09-08',
    vendorName: 'Siripuram Tech Towers',
    description: 'High-speed leased line fiber internet, electricity & workspace facility maintenance.',
  },
  {
    id: 'EXP-704',
    category: 'Marketing & Ads',
    amount: 25000,
    date: '2026-09-12',
    vendorName: 'Meta Ads Manager',
    description: 'Direct agency promotional ad spend for DDS Expo agency client acquisition campaign.',
  },
  {
    id: 'EXP-705',
    category: 'Salaries',
    amount: 345000,
    date: '2026-09-01',
    description: 'Monthly payroll disbursement for tech, design, AI engineers and sales executives.',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'TXN-01',
    type: 'Income',
    amount: 88942.5,
    category: 'Client Payment',
    date: '2026-06-28',
    referenceId: 'INV-2026-101',
    partyName: 'Vizag Port Logistics Ltd',
    paymentMethod: 'Bank Transfer',
  },
  {
    id: 'TXN-02',
    type: 'Income',
    amount: 37170,
    category: 'Client Payment',
    date: '2026-08-04',
    referenceId: 'INV-2026-103',
    partyName: 'Aura Organic Health',
    paymentMethod: 'UPI / GPay',
  },
  {
    id: 'TXN-03',
    type: 'Income',
    amount: 50150,
    category: 'Client Payment',
    date: '2026-08-12',
    referenceId: 'INV-2026-104',
    partyName: 'Sethi Retail Network',
    paymentMethod: 'Bank Transfer',
  },
  {
    id: 'TXN-04',
    type: 'Expense',
    amount: 345000,
    category: 'Salaries',
    date: '2026-09-01',
    referenceId: 'EXP-705',
    partyName: 'DDS Staff Payroll',
    paymentMethod: 'Bank Transfer',
  },
  {
    id: 'TXN-05',
    type: 'Expense',
    amount: 14200,
    category: 'Cloud & Servers',
    date: '2026-09-02',
    referenceId: 'EXP-701',
    partyName: 'Google Cloud & AWS',
    paymentMethod: 'Corporate Card',
  },
  {
    id: 'TXN-06',
    type: 'Expense',
    amount: 18500,
    category: 'Software Licenses',
    date: '2026-09-05',
    referenceId: 'EXP-702',
    partyName: 'OpenAI / Midjourney',
    paymentMethod: 'Corporate Card',
  },
  {
    id: 'TXN-07',
    type: 'Expense',
    amount: 25000,
    category: 'Marketing & Ads',
    date: '2026-09-12',
    referenceId: 'EXP-704',
    partyName: 'Meta Ads Manager',
    paymentMethod: 'Corporate Card',
  },
];

export const INITIAL_SALES_TARGETS: SalesTarget[] = [
  {
    id: 'TRG-01',
    employeeId: 'EMP-04',
    employeeName: 'Mr. Sanjay Kumar',
    period: 'Monthly',
    year: 2026,
    monthOrQuarter: 'September',
    targetAmount: 500000,
    achievedAmount: 320000,
  },
  {
    id: 'TRG-02',
    employeeId: 'EMP-04',
    employeeName: 'Mr. Sanjay Kumar',
    period: 'Quarterly',
    year: 2026,
    monthOrQuarter: 'Q3 (Jul - Sep)',
    targetAmount: 1500000,
    achievedAmount: 1210000,
  },
];

export const INITIAL_INVENTORY: InventoryProduct[] = [
  {
    id: 'PRD-101',
    name: 'Apple MacBook Pro M3 16GB (Developer Unit)',
    sku: 'HW-MBP-M3-16',
    category: 'Laptops',
    quantity: 8,
    warehouse: 'Main Tech Lab - Visakhapatnam',
    purchasePrice: 169000,
    sellingPrice: 199000,
    minAlertQty: 2,
  },
  {
    id: 'PRD-102',
    name: 'Dell UltraSharp 27" 4K HDR Monitor',
    sku: 'HW-MON-4K-27',
    category: 'Peripherals',
    quantity: 14,
    warehouse: 'Main Tech Lab - Visakhapatnam',
    purchasePrice: 38000,
    sellingPrice: 45000,
    minAlertQty: 3,
  },
  {
    id: 'PRD-103',
    name: 'Cisco Gigabit Managed Switch 24-Port',
    sku: 'NET-CSCO-24G',
    category: 'Networking',
    quantity: 3,
    warehouse: 'Server Room Alpha',
    purchasePrice: 32000,
    sellingPrice: 40000,
    minAlertQty: 1,
  },
  {
    id: 'PRD-104',
    name: 'Adobe Creative Cloud Team License (Annual)',
    sku: 'SW-ADB-CC-YR',
    category: 'Software Licenses',
    quantity: 10,
    warehouse: 'Digital Asset Vault',
    purchasePrice: 48000,
    sellingPrice: 55000,
    minAlertQty: 2,
  },
];

export const INITIAL_STOCK_MOVEMENTS: StockMovement[] = [
  {
    id: 'SM-01',
    productId: 'PRD-101',
    productName: 'Apple MacBook Pro M3 16GB',
    type: 'In',
    quantity: 5,
    date: '2026-08-15',
    reason: 'New developer hardware onboarding purchase PO-301',
    performedBy: 'Mr. Srikanth',
  },
  {
    id: 'SM-02',
    productId: 'PRD-102',
    productName: 'Dell UltraSharp 27" 4K Monitor',
    type: 'Out',
    quantity: 2,
    date: '2026-09-01',
    reason: 'Assigned to Senior AI Engineers workstation',
    performedBy: 'Mrs. Rama Devi',
  },
];

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'VND-01',
    name: 'InfraTech Hardware Solutions Pvt Ltd',
    contactPerson: 'Kalyan Chakravarthy',
    phone: '+91 9848123987',
    email: 'kalyan@infratechvizag.com',
    address: 'Dwaraka Nagar, Visakhapatnam, AP',
    gstNumber: '37INFRA1234F1Z9',
    servicesSupplied: 'Laptops, 4K Displays, Networking Switches & Servers',
    status: 'Active',
  },
  {
    id: 'VND-02',
    name: 'CloudScale Networks India',
    contactPerson: 'Meera Nambiar',
    phone: '+91 9900112288',
    email: 'billing@cloudscale.in',
    address: 'MG Road, Bengaluru, KA',
    gstNumber: '29CLOUD9876C1Z3',
    servicesSupplied: 'Dedicated IP subnets, Fiber line leased circuits',
    status: 'Active',
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'PO-301',
    vendorId: 'VND-01',
    vendorName: 'InfraTech Hardware Solutions',
    requestDate: '2026-08-10',
    expectedDate: '2026-08-15',
    status: 'Received',
    totalAmount: 845000,
    itemsDescription: '5x Apple MacBook Pro M3 + 4x Dell 27" 4K Monitors',
    approvedBy: 'Mr. Dhanunjay',
  },
  {
    id: 'PO-302',
    vendorId: 'VND-02',
    vendorName: 'CloudScale Networks India',
    requestDate: '2026-09-05',
    expectedDate: '2026-09-12',
    status: 'Approved',
    totalAmount: 48000,
    itemsDescription: 'Quarterly High-Speed Leased Line 1Gbps Fiber Bandwidth',
    approvedBy: 'Mr. Srikanth',
  },
];

export const INITIAL_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 'TCK-801',
    customerId: 'CUST-501',
    customerName: 'Mr. Arjun Sharma (Vizag Port Logistics)',
    subject: 'Port Berthing webhook returning 504 on heavy cargo peak hours',
    description: 'During 5 PM container shift synchronization, the API response times out after 30 seconds.',
    category: 'Website issue',
    priority: 'Urgent',
    assignedEmployeeId: 'EMP-05',
    assignedEmployeeName: 'Alex Rivera',
    status: 'In Progress',
    createdDate: '2026-09-16 11:45',
  },
  {
    id: 'TCK-802',
    customerId: 'CUST-502',
    customerName: 'Ritika Rao (Aura Organic Health)',
    subject: 'Request for updated Meta pixel tracking for Instagram shopping catalog',
    description: 'Need assistance syncing new turmeric supplement collection with Catalog Manager.',
    category: 'Marketing request',
    priority: 'Medium',
    assignedEmployeeId: 'EMP-04',
    assignedEmployeeName: 'Mr. Sanjay Kumar',
    status: 'Resolved',
    createdDate: '2026-09-14 15:20',
    resolution: 'Custom Conversion event tag added and tested on GTM container.',
  },
  {
    id: 'TCK-803',
    customerId: 'CUST-503',
    customerName: 'Vikram Sethi (Sethi Retail Network)',
    subject: 'Add 2 new store locations to WhatsApp automated store locator query',
    description: 'Please add Connaught Place extension and Noida Sector 18 stores into the database.',
    category: 'App issue',
    priority: 'Low',
    assignedEmployeeId: 'EMP-07',
    assignedEmployeeName: 'Kiran Varma',
    status: 'Open',
    createdDate: '2026-09-18 09:10',
  },
];

export const INITIAL_DOCUMENTS: ErpDocument[] = [
  {
    id: 'DOC-101',
    title: 'Vizag Port Logistics Master Service Agreement & SLA.pdf',
    category: 'Contracts',
    fileType: 'PDF',
    fileSize: '2.4 MB',
    uploadDate: '2026-06-18',
    uploadedBy: 'Mr. Dhanunjay',
    relatedEntityName: 'Vizag Port Logistics Ltd',
  },
  {
    id: 'DOC-102',
    title: 'Quotation QT-2026-001 Approved Copy.pdf',
    category: 'Quotations',
    fileType: 'PDF',
    fileSize: '840 KB',
    uploadDate: '2026-06-15',
    uploadedBy: 'Mr. Sanjay Kumar',
    relatedEntityName: 'QT-2026-001',
  },
  {
    id: 'DOC-103',
    title: 'DDS Expo Company Registration & GST Certificate.pdf',
    category: 'Company Documents',
    fileType: 'PDF',
    fileSize: '1.2 MB',
    uploadDate: '2026-01-10',
    uploadedBy: 'Mrs. Rama Devi',
    relatedEntityName: 'DDS Expo Technologies',
  },
  {
    id: 'DOC-104',
    title: 'Invoice INV-2026-101 Paid Receipt.pdf',
    category: 'Invoices',
    fileType: 'PDF',
    fileSize: '410 KB',
    uploadDate: '2026-06-29',
    uploadedBy: 'Priya Sharma',
    relatedEntityName: 'INV-2026-101',
  },
  {
    id: 'DOC-105',
    title: 'Sethi Retail WhatsApp Bot Architecture Blueprint.pdf',
    category: 'Project Documents',
    fileType: 'PDF',
    fileSize: '4.8 MB',
    uploadDate: '2026-08-05',
    uploadedBy: 'Alex Rivera',
    relatedEntityName: 'PRJ-403',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-1',
    title: 'New Lead Generated from Website!',
    message: 'Deepak Vats from CyberShield requested Brand Identity design via website contact form.',
    type: 'lead',
    timestamp: '10 mins ago',
    read: false,
    linkSection: 'crm-leads',
  },
  {
    id: 'NOTIF-2',
    title: 'Invoice Overdue Notice',
    message: 'INV-2026-102 for Vizag Port Logistics (₹53,365.50) passed due date.',
    type: 'invoice',
    timestamp: '2 hours ago',
    read: false,
    linkSection: 'sales-invoices',
  },
  {
    id: 'NOTIF-3',
    title: 'Today\'s Follow-up Alert',
    message: 'Video call scheduled with Manish Verma (Apex Cloud) today at 11:30 AM.',
    type: 'followup',
    timestamp: '3 hours ago',
    read: false,
    linkSection: 'crm-followups',
  },
  {
    id: 'NOTIF-4',
    title: 'Task Assigned',
    message: 'Alex Rivera assigned to Razorpay Webhooks integration on PRJ-401.',
    type: 'task',
    timestamp: 'Yesterday',
    read: true,
    linkSection: 'projects-tasks',
  },
  {
    id: 'NOTIF-5',
    title: 'Payment Received',
    message: '₹37,170 received from Aura Organic Health via UPI.',
    type: 'payment',
    timestamp: 'Aug 4',
    read: true,
    linkSection: 'sales-payments',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'AUD-901',
    user: 'Mr. Sanjay Kumar',
    role: 'Sales',
    action: 'Created New Lead',
    module: 'CRM',
    record: 'LEAD-105 (Deepak Vats)',
    date: '2026-09-18',
    time: '09:05:22',
    newValue: 'Source: WhatsApp, Value: ₹50,000',
  },
  {
    id: 'AUD-902',
    user: 'Mr. Srikanth',
    role: 'Manager',
    action: 'Updated Project Progress',
    module: 'Projects',
    record: 'PRJ-403 (Sethi Retail AI Bot)',
    date: '2026-09-17',
    time: '16:45:10',
    previousValue: 'Progress: 80%',
    newValue: 'Progress: 90%',
  },
  {
    id: 'AUD-903',
    user: 'Priya Sharma',
    role: 'Accounts',
    action: 'Generated Milestone Invoice',
    module: 'Finance',
    record: 'INV-2026-105 (₹50,150)',
    date: '2026-09-16',
    time: '11:12:00',
    newValue: 'Status: Sent to customer',
  },
  {
    id: 'AUD-904',
    user: 'Mr. Dhanunjay',
    role: 'Super Admin',
    action: 'Approved Quotation Conversion',
    module: 'Sales',
    record: 'QT-2026-003 -> PRJ-403',
    date: '2026-08-01',
    time: '10:00:34',
    previousValue: 'Status: Sent',
    newValue: 'Status: Accepted & Project Created',
  },
];

export const INITIAL_COMMUNICATIONS: CommunicationEvent[] = [
  {
    id: 'COMM-01',
    customerId: 'CUST-501',
    leadId: 'LEAD-101',
    type: 'Call',
    timestamp: '2026-09-15 11:00',
    summary: 'Discussed staging deployment status and berthing API rate limits.',
    staffName: 'Mr. Srikanth',
  },
  {
    id: 'COMM-02',
    customerId: 'CUST-502',
    type: 'WhatsApp',
    timestamp: '2026-09-14 16:30',
    summary: 'Shared performance report of last week\'s Instagram reels reach (380k impressions).',
    staffName: 'Mr. Sanjay Kumar',
  },
  {
    id: 'COMM-03',
    leadId: 'LEAD-102',
    type: 'Email',
    timestamp: '2026-09-14 18:15',
    summary: 'Emailed official quotation QT-2026-004 for customer support AI automation agent.',
    staffName: 'Mr. Sanjay Kumar',
  },
];
